# Generated by Django 4.1.4 on 2022-12-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmar', models.CharField(max_length=50, verbose_name='Confirmar')),
            ],
        ),
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='')),
                ('confirmar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitacionAPP.confirmacion')),
            ],
        ),
    ]
